name: Build

on: push

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: "requirements/packaging.txt"

    - name: Install Qt lrelease
      run: |
        sudo apt-get update
        sudo apt-get install qttools5-dev-tools

    - name: Install Python requirements
      run: pip install -r requirements/packaging.txt

    - name: Build package
      run: |
        qgis-plugin-ci package dev-${GITHUB_SHA}
        mkdir tmp
        unzip felt.dev-${GITHUB_SHA}.zip -d tmp

    - uses: actions/upload-artifact@v2
      with:
        name: felt.dev-${GITHUB_SHA}.zip
        path: tmp
