on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'felt' && contains(github.ref, 'refs/tags/')

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/packaging.txt"

       # Needed if the plugin is using Transifex, to have the lrelease command
       # - name: Install Qt lrelease
       #   run: |
       #    sudo apt-get update
       #    sudo apt-get install qt5-make qttools5-dev-tools

      - name: Install Python requirements
        run: pip install -r requirements/packaging.txt

      - name : Fetch current changelog
        run: qgis-plugin-ci changelog ${{ env.RELEASE_VERSION }} >> release.md

      - name: Deploy plugin
        run: >-
          qgis-plugin-ci
          release ${{ env.RELEASE_VERSION }}
          --github-token ${{ secrets.GITHUB_TOKEN }}
